lab11.932202.Sviridov.Fedor-main/Lab1/Models/Class.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab1.Models
{
    public class mylist
    {
        public ArrayList values;

        public mylist(int add, int sub,int mult,double div,int value1,int value2 )
        {
            values = new ArrayList();
            values.Add(add);
            values.Add(sub);
            values.Add(mult);
            values.Add(div);
            values.Add(value1);
            values.Add(value2);
        }
    }
}

lab11.932202.Sviridov.Fedor-main/Lab1/Models/ErrorViewModel.cs
using System;

namespace Lab1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab11.932202.Sviridov.Fedor-main/Lab1/Controllers/CalcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab1.Models;
using Lab1.Services;

namespace Lab1.Controllers
{
    public class CalcController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult UsingModelCalc()
        {
            Random rand = new Random();
            int value1 = rand.Next(0, 10);
            int value2 = rand.Next(0, 10);
            int add = value1 + value2;
            int sub = value1 - value2;
            int mult = value1 * value2;
            double div = (double)value1 / (double)value2;
            mylist l = new mylist(add,sub,mult,div,value1,value2);

            if (value2 != 0)
            {
                return View(l);
            }
            else
            {
                return View("ZeroErrorCalc");
            }
        }
    
        public IActionResult ViewDataCalc()
        {
        
            Random rand = new Random();
            int value1 = rand.Next(0, 10);
            int value2 = rand.Next(0, 10);
            
            int add = value1 + value2;
            int sub = value1 - value2;
            int mult = value1 * value2;
            double div = (double)value1 / (double)value2;
            
            ViewData["Value1"] = value1;
            ViewData["Value2"] = value2;
            ViewData["add"] = add;
            ViewData["sub"] = sub;
            ViewData["mult"] = mult;
            ViewData["div"] = div;

            if (value2 != 0)
            {
                return View("ViewDataCalc");
            }
            else
            {
                return View("ZeroErrorCalc");
            }
        }

        public IActionResult ViewBagCalc()
        {
            Random rand = new Random();
            int value1 = rand.Next(0, 10);
            int value2 = rand.Next(0, 10);

            ViewBag.Value1 = value1;
            ViewBag.Value2 = value2;

            int add = value1 + value2;
            int sub = value1 - value2;
            int mult = value1 * value2;
            double div = (double)value1 / (double)value2;

            ViewBag.add = add;
            ViewBag.sub = sub;
            ViewBag.mult = mult;
            ViewBag.div = div;

            if (value2 != 0)
            {
                return View("ViewBagCalc");
            }
            else
            {
                return View("ZeroErrorCalc");
            }
        }

        
        public IActionResult ServiceInjectionCalc()
        {
            return View();
        }
    }
}

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h2>Calc Service Demonstration</h2>
<ul>
    <li>
        <a href="/Calc/UsingModelCalc">Using Model Calc</a>
    </li>
    <li>
        <a href="/Calc/ViewDataCalc">Using ViewData Calc</a>
    </li>
    <li>
        <a href="/Calc/ViewBagCalc">Using ViewBag Calc</a>
    </li>
    <li>
        <a href="/Calc/ServiceInjectionCalc">Using Service Injection Calc</a>
    </li>
</ul>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/ServiceInjectionCalc.cshtml
@inject Lab1.Services.HTMLSender calc

@{

    ViewData["Title"] = "ServiceInjectionCalc";
}

<h2>ServiceInjectionCalc</h2>
<div>Первое число: @calc.Value1</div>
<div>Второе число: @calc.Value2</div>
<div>Сумма: @calc.Value1 + @calc.Value2 = @calc.add()</div>
<div>Разность: @calc.Value1 - @calc.Value2 = @calc.sub()</div>
<div>Умножение: @calc.Value1 * @calc.Value2 = @calc.mult()</div>
<div>
    Div: @calc.Value1 / @calc.Value2 = @if (calc.div() == -1)
    {
        @: error
    }
    else
    {
        @calc.div()
    }
</div>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/UsingModelCalc.cshtml
@model mylist
@{
    ViewData["Title"] = "UsingModelCalc";
}

<h2>UsingModelCalc</h2>
<div>Первое число: @Model.values[4]</div>
<div>Второе число: @Model.values[5]</div>
<div>Сумма: @Model.values[4] + @Model.values[5] = @Model.values[0]</div>
<div>Разность: @Model.values[4] - @Model.values[5] = @Model.values[1]</div>
<div>Умножение: @Model.values[4] * @Model.values[5] = @Model.values[2]</div>
<div>Деление: @Model.values[4] / @Model.values[5] = @Model.values[3]</div>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/ViewBagCalc.cshtml
@{
    ViewData["Title"] = "ViewBagCalc";
}

<h2>ViewBagCalc</h2>
<div>Первое число: @ViewBag.Value1</div>
<div>Второе число: @ViewBag.Value2</div>
<div>Сумма: @ViewBag.value1 + @ViewBag.value2 = @ViewBag.add</div>
<div>Разность: @ViewBag.value1 - @ViewBag.value2 = @ViewBag.sub</div>
<div>Умножение: @ViewBag.value1 * @ViewBag.value2 = @ViewBag.mult</div>
<div>Деление: @ViewBag.value1 / @ViewBag.value2 = @ViewBag.div</div>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/ViewDataCalc.cshtml
@{
    ViewData["Title"] = "ViewDataCalc";
}

<h2>ViewDataCalc</h2>
<div>Первое число: @ViewData["Value1"]</div>
<div>Второе число: @ViewData["Value2"]</div>
<div>Сумма: @ViewData["Value1"] + @ViewData["Value2"] = @ViewData["add"]</div>
<div>Разность: @ViewData["Value1"] - @ViewData["Value2"] = @ViewData["sub"]</div>
<div>Умножение: @ViewData["Value1"] * @ViewData["Value2"] = @ViewData["mult"]</div>
<div>Деление: @ViewData["Value1"] / @ViewData["Value2"] = @ViewData["div"]</div>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Calc/ZeroErrorCalc.cshtml
@{
    ViewData["Title"] = "ZeroErrorCalc";
}

<h2>Упс! Деление на ноль</h2>

lab11.932202.Sviridov.Fedor-main/Lab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    
                </button>
                <a asp-area="" asp-controller="Calc" asp-action="Index" class="navbar-brand">Backend1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Calc" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Backend1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>